### ISSUE TITLE
arguments

### ISSUE THREAD

**Issue by itsftw** [bozelosp/download_scholar_pdfs#1]
Hello,
i would like to let you know that your script requires all the arguments even if there is no multicore support, running it without the 2nd and 3rd argument gives error ( not counting sys.argv[0]) .I had to type : 
python batch_download.py list_of_dois_or_titles.txt false 1 
Please update the readme.Thanks for your work.It's really appreciated

**Comment by bozelosp** [comment]
Hi, I've addressed that bothering issue. It now detects if there multiprocessing is installed, and if you want to use more than 1 cores. Check the updated README.
