### ISSUE TITLE
[Feature Request] Implement a proper pause/resume 

### ISSUE THREAD

**Issue by Nottt** [bozelosp/download_scholar_pdfs#3]
Thanks for this amazing software!

The only issue is that if your server crash for any reason / the script stop working you have to restart from the 0. 

Would be asking too much to implement a proper pause / resume after crash system?

Also your script seems to just stop running and exit without any error or issues...it just exit...

I'm running your script with python batch_download.py DOI_60000000-64871768.txt false 1 > python.log &

Every time it exists I see nothing on python.log no error, nothing.

**Comment by bozelosp** [comment]
Hi and many thanks for utilizing the script. 

Apologies for any inconvenience you may have experienced, due to my amateur implementation.

I've tried to address the issue of "proper pause / resume after crash", by listing the PDF files saved in the working directory and excluding them from the downloading process (when scripts runs anew).

**Comment by Nottt** [comment]
No need to apologize for anything lol :)

I think the biggest issue is why it's just exiting without any error, anything really. The only time I got a error message in my console it was : 

```
File "batch_download.py", line 109, in <module>
    work(dois)
  File "batch_download.py", line 91, in work
    download_doi_pdf(doi)
  File "batch_download.py", line 41, in download_doi_pdf
    response = urllib2.urlopen(req)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 502: Bad Gateway
```

I can help you debug this, what is the proper way to log the output of the script then? So far seems to be working stable now, I left my putty session open but I don't know if was that or no ( I still send them to the background with & )
